/*
 * FormPrincipal.java
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jccr.Vista;

import Complementos.*;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 * Formulario Principal de la aplicación
 * @author Grupo 4 Plataformas de Desarrollo de Software
 * Version 1.0
 */
public class FormPrincipal extends javax.swing.JFrame {

    private IFormProductos myIFormProductos;
    private IFormUsuario myIFormUsuario;
    private IFormGuias myIFormGuias;
    
    /** 
     * Creates new form FormPrincipal
     * @param myFormLogin 
     */
    public FormPrincipal(FormLogin myFormLogin) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/Iconos/1. Icono Inicio.png")).getImage());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPanelPrincipal = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        cmdFacturas = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        cmdClientes = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        cmdProductos = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMERCIALIZADORA GREMLINS");

        jToolBar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar2.setRollover(true);

        cmdFacturas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/11. Venta.png"))); // NOI18N
        cmdFacturas.setMnemonic('F');
        cmdFacturas.setToolTipText("Facturar");
        cmdFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdFacturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFacturasActionPerformed(evt);
            }
        });
        cmdFacturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdFacturasKeyPressed(evt);
            }
        });
        jToolBar2.add(cmdFacturas);
        jToolBar2.add(jSeparator6);

        cmdClientes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/11. Cliente.png"))); // NOI18N
        cmdClientes.setMnemonic('C');
        cmdClientes.setToolTipText("Usuarios");
        cmdClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdClientesActionPerformed(evt);
            }
        });
        cmdClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdClientesKeyPressed(evt);
            }
        });
        jToolBar2.add(cmdClientes);
        jToolBar2.add(jSeparator12);

        cmdProductos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/17. Producto.png"))); // NOI18N
        cmdProductos.setMnemonic('P');
        cmdProductos.setToolTipText("Productos");
        cmdProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProductosActionPerformed(evt);
            }
        });
        cmdProductos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdProductosKeyPressed(evt);
            }
        });
        jToolBar2.add(cmdProductos);
        jToolBar2.add(jSeparator13);

        cmdSalir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/10. Salir.png"))); // NOI18N
        cmdSalir.setMnemonic('S');
        cmdSalir.setToolTipText("Salir");
        cmdSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        cmdSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdSalirKeyPressed(evt);
            }
        });
        jToolBar2.add(cmdSalir);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jDesktopPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/** 
 * Metodo getjdpHeight
 * Retorna la altura del jdp 
 */
public int getjdpHeight() {
    return this.jDesktopPanelPrincipal.getHeight();
}

/** 
 * Metodo getjdpWidth
 * Retorna el ancho del jdp  
 */
public int getjdpWidth(){
    return this.jDesktopPanelPrincipal.getWidth();
}

/** 
 * Metodo getjdpHeight
 * Retorna la altura del jdp 
 */
public int getjPanelBotonesHeight() {
    return this.jDesktopPanelPrincipal.getHeight();
}

public void setLocation(){
    int height = this.getjdpHeight();
    int width = this.getjdpWidth();
    this.setLocation ((width - this.getWidth ()) / 2,(height - this.getHeight ()) / 2);
}

//METODO QUE DEVUELVE UN VALOR BOOLEAN PARA SABER SI UN JINTERNALFRAME ESTA ABIERTO O NO
public boolean verificarVentana(Object obj){
    JInternalFrame[] activos = this.jDesktopPanelPrincipal.getAllFrames();
    boolean cerrado = true;
    int i = 0;
    while (i<activos.length && cerrado){
        if(activos[i] == obj){
            cerrado = false;
        }
        i++;
    }
    return cerrado;
}

private void cmdFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFacturasActionPerformed
// TODO add your handling code here:
    if(this.verificarVentana(this.myIFormGuias)){
        this.myIFormGuias = new IFormGuias(this);
        this.jDesktopPanelPrincipal.add(this.myIFormGuias);
        this.myIFormGuias.show();
    }
    else{
        Ventana.warning("La ventana Guias ya esta abierta.", "SISTEMA");
    }
}//GEN-LAST:event_cmdFacturasActionPerformed

private void cmdFacturasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdFacturasKeyPressed
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdFacturasActionPerformed(null);
    }
}//GEN-LAST:event_cmdFacturasKeyPressed

private void cmdClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdClientesActionPerformed
// TODO add your handling code here:
if(this.verificarVentana(this.myIFormUsuario)){
        this.myIFormUsuario = new IFormUsuario(this);
        this.jDesktopPanelPrincipal.add(this.myIFormUsuario);
        this.myIFormUsuario.show();
    }
    else{
        Ventana.warning("La ventana Usuarios ya esta abierta.", "SISTEMA");
    }
}//GEN-LAST:event_cmdClientesActionPerformed

private void cmdClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdClientesKeyPressed
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdClientesActionPerformed(null);
    }
}//GEN-LAST:event_cmdClientesKeyPressed

private void cmdProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProductosActionPerformed
// TODO add your handling code here:
    if(this.verificarVentana(this.myIFormProductos)){
        this.myIFormProductos = new IFormProductos(this);
        this.jDesktopPanelPrincipal.add(this.myIFormProductos);
        this.myIFormProductos.show();
    }
    else{
        Ventana.warning("La ventana Productos ya esta abierta.", "SISTEMA");
    }
}//GEN-LAST:event_cmdProductosActionPerformed

private void cmdProductosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdProductosKeyPressed
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdProductosActionPerformed(null);
    }
}//GEN-LAST:event_cmdProductosKeyPressed

private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_cmdSalirActionPerformed

private void cmdSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdSalirKeyPressed
// TODO add your handling code here:
     int t=(int) evt.getKeyChar();
    if(t==10){
        this.dispose();
    }
}//GEN-LAST:event_cmdSalirKeyPressed

    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdClientes;
    private javax.swing.JButton cmdFacturas;
    private javax.swing.JButton cmdProductos;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JDesktopPane jDesktopPanelPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables

}
