/*
 * IFormUsuarios.java
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jccr.Vista;

import Complementos.*;
import java.net.MalformedURLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import com.jccr.Controlador.UsuarioControl;

/**
 * IFormUsuarios Es el formulario para el control de usuario de inicion de sesion.
 * @author Grupo 4 Plataformas de Desarrollo de Software
 * Version 1.0
 */
public class IFormUsuarios extends javax.swing.JFrame {
    
    private final UsuarioControl myControlador;
    private JDialogUsuario myJDialogUsuario;
    private DefaultTableModel dtm_Listado;
    private final DefaultTableCellRenderer modeloCentrar = new DefaultTableCellRenderer();
    private final DefaultTableCellRenderer modeloAlinearDerecha = new DefaultTableCellRenderer();
    //Usuario de la Base de datos.
    private static final String TITULO = "Usuarios";

    /**
     * Metodo Constructor
     * @throws MalformedURLException
     * @throws ParseException 
     */
    public IFormUsuarios() throws MalformedURLException, ParseException{
        initComponents();
        this.myControlador = new UsuarioControl();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/1. Icono Inicio.png")).getImage());
        this.modeloCentrar.setHorizontalAlignment(SwingConstants.CENTER);
        this.modeloAlinearDerecha.setHorizontalAlignment(SwingConstants.RIGHT);
        this.inicio();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicioSesion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        cmdNuevo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        cmdModificar = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        cmdEliminar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        cmdSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaListadoUauarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de Sesión");

        jPanelInicioSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        cmdNuevo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/3. Agregar.png"))); // NOI18N
        cmdNuevo.setMnemonic('N');
        cmdNuevo.setToolTipText("Nuevo Registro");
        cmdNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        cmdNuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdNuevoKeyPressed(evt);
            }
        });
        jToolBar1.add(cmdNuevo);
        jToolBar1.add(jSeparator5);

        cmdModificar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/4. Modificar.png"))); // NOI18N
        cmdModificar.setMnemonic('M');
        cmdModificar.setToolTipText("Modificar");
        cmdModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });
        cmdModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdModificarKeyPressed(evt);
            }
        });
        jToolBar1.add(cmdModificar);
        jToolBar1.add(jSeparator9);

        cmdEliminar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/7. Borrar.png"))); // NOI18N
        cmdEliminar.setMnemonic('L');
        cmdEliminar.setToolTipText("Borrar");
        cmdEliminar.setFocusable(false);
        cmdEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        cmdEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdEliminarKeyPressed(evt);
            }
        });
        jToolBar1.add(cmdEliminar);
        jToolBar1.add(jSeparator8);

        cmdSalir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        cmdSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/10. Salir.png"))); // NOI18N
        cmdSalir.setMnemonic('S');
        cmdSalir.setToolTipText("Salir");
        cmdSalir.setFocusable(false);
        cmdSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmdSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        cmdSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdSalirKeyPressed(evt);
            }
        });
        jToolBar1.add(cmdSalir);

        tablaListadoUauarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaListadoUauarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListadoUauarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListadoUauariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaListadoUauarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelInicioSesionLayout = new javax.swing.GroupLayout(jPanelInicioSesion);
        jPanelInicioSesion.setLayout(jPanelInicioSesionLayout);
        jPanelInicioSesionLayout.setHorizontalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelInicioSesionLayout.setVerticalGroup(
            jPanelInicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioSesionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public UsuarioControl getmyControlador() {
        return myControlador;
    }
    
    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
        // TODO add your handling code here:
            int IdUsu = this.getmyControlador().getNumRegistroUsuario();
            this.myJDialogUsuario = new JDialogUsuario(this, true, IdUsu, true, false);
            this.myJDialogUsuario.setVisible(true);
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdNuevoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdNuevoKeyPressed
        // TODO add your handling code here:
        int t = (int) evt.getKeyChar();
        if(t == 10){
            this.cmdNuevoActionPerformed(null);
        }
    }//GEN-LAST:event_cmdNuevoKeyPressed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        // TODO add your handling code here:
        if(this.tablaListadoUauarios.getRowCount() > 0 && this.tablaListadoUauarios.getSelectedRowCount() > 0 ){
            int ind = this.tablaListadoUauarios.getSelectedRow();
            int IdUsu = Integer.parseInt(this.dtm_Listado.getValueAt(ind, 0).toString());
            this.myJDialogUsuario = new JDialogUsuario(this, true, IdUsu, false, true);
                this.myJDialogUsuario.setVisible(true);
           }
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdModificarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdModificarKeyPressed
        // TODO add your handling code here:
        int t = (int) evt.getKeyChar();
        if(t == 10){
            this.cmdModificarActionPerformed(null);
        }
    }//GEN-LAST:event_cmdModificarKeyPressed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        // TODO add your handling code here:
        if(this.tablaListadoUauarios.getRowCount() > 0 && this.tablaListadoUauarios.getSelectedRowCount() > 0 ){
            int ind = this.tablaListadoUauarios.getSelectedRow();
            int IdUsu = Integer.parseInt(this.dtm_Listado.getValueAt(ind, 0).toString());
            Ventana.imp(this.getmyControlador().eliminarUsuario(IdUsu), "Eliminar usuario.");
            this.cargarTablaUsuarios();
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdEliminarKeyPressed
        // TODO add your handling code here:
        int t = (int) evt.getKeyChar();
        if(t == 10){
            this.cmdEliminarActionPerformed(null);
        }
    }//GEN-LAST:event_cmdEliminarKeyPressed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdSalirKeyPressed
        // TODO add your handling code here:
        int t = (int) evt.getKeyChar();
        if(t == 10){
            this.cmdSalirActionPerformed(null);
        }
    }//GEN-LAST:event_cmdSalirKeyPressed

    private void tablaListadoUauariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListadoUauariosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()>1){
            this.cmdModificarActionPerformed(null);
        }
    }//GEN-LAST:event_tablaListadoUauariosMouseClicked
/**
 * Metodo inicio()
 * 
 */
private void inicio(){
    this.cargarTablaUsuarios();
}


public final void cargarTablaUsuarios(){
    this.getmyControlador().cargarUsuarios("");
    Object[] NombreColumnas = {"ID USUARIO", "NOMBRE", "IDENTIFICACION", "ESTADO"};
    this.dtm_Listado = new DefaultTableModel(NombreColumnas, 0){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    this.tablaListadoUauarios.setModel(this.dtm_Listado);
    this.tablaListadoUauarios.getColumnModel().getColumn(0).setPreferredWidth(30);
    this.tablaListadoUauarios.getColumnModel().getColumn(1).setPreferredWidth(100);
    this.tablaListadoUauarios.getColumnModel().getColumn(2).setPreferredWidth(60);
    this.tablaListadoUauarios.getColumnModel().getColumn(3).setPreferredWidth(60);
    this.tablaListadoUauarios.getColumnModel().getColumn(0).setCellRenderer(this.modeloCentrar);
    this.tablaListadoUauarios.getColumnModel().getColumn(1).setCellRenderer(this.modeloCentrar);
    //TableRowSorter<TableModel> tablaOrdenada = new TableRowSorter<TableModel>(this.dtm_Listado);
    //this.tablaListadoUauarios.setRowSorter(tablaOrdenada);
    
    int x = this.getmyControlador().getMyUsuario().size();
    for(int i = 0; i < x; i++){
        String estado = "ACTIVO";
        int idUsu = this.getmyControlador().getMyUsuario().get(i).getUsuId();
        String nomUsu = this.getmyControlador().getMyUsuario().get(i).getUsuNom();
        String usuIdent = this.getmyControlador().getMyUsuario().get(i).getUsuIdent();
        int estUsu = this.getmyControlador().getMyUsuario().get(i).getUsuEstado();
        if(estUsu == 0){
            estado = "INACTIVO";
        }
            Object[] nuevaFila = {idUsu, nomUsu, usuIdent, estado};
            this.dtm_Listado.addRow(nuevaFila);
    }
    this.getmyControlador().getMyUsuario().clear();
}


    /**
    * Metodo main 
    * es el metodo principal de la aplicacion
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new IFormUsuarios().setVisible(true);
            } catch (MalformedURLException | ParseException ex) {
                Logger.getLogger(IFormUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInicioSesion;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tablaListadoUauarios;
    // End of variables declaration//GEN-END:variables

}
