/*
 * JDialogUsuario.java
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jccr.Vista;
import Complementos.*;

/**
 * Formulario para crear y modificar usuarios 
 * @author Grupo 4 Plataformas de Desarrollo de Software
 * Version 1.0
 */
public class JDialogUsuario extends javax.swing.JDialog {

    private final IFormUsuarios myIFormUsuarios;
    private final boolean nuevo;
    private final boolean modificar;
    private final int idUser;      
    
    /** 
     * Creates new form JDialogUsuario
     * @param myIFormUsuarios
     * @param modal
     * @param idUser
     * @param nuevo
     * @param modificar 
     */
    public JDialogUsuario(IFormUsuarios myIFormUsuarios, boolean modal, 
            int idUser, boolean nuevo, boolean modificar) {
        super(myIFormUsuarios, modal);
        initComponents();
        this.myIFormUsuarios = myIFormUsuarios;
        this.setLocationRelativeTo(this.myIFormUsuarios);
        this.idUser = idUser;
        this.nuevo = nuevo;
        this.modificar = modificar;
        this.iniciar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnGuardar = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel();
        jPasswordUsu = new javax.swing.JPasswordField();
        lblConfClave = new javax.swing.JLabel();
        jPasswordConfirUsu = new javax.swing.JPasswordField();
        lblEstado = new javax.swing.JLabel();
        cmbEstadoUsu = new javax.swing.JComboBox();
        lblIdent = new javax.swing.JLabel();
        txtIdent = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/8. Guardar.png"))); // NOI18N
        btnGuardar.setMnemonic('G');
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        btnGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarKeyPressed(evt);
            }
        });
        jToolBar1.add(btnGuardar);
        jToolBar1.add(jSeparator8);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/10. Salir.png"))); // NOI18N
        btnSalir.setMnemonic('S');
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSalirKeyPressed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        lblNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblNombre.setText("Nombre ");

        txtNom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblClave.setText("Contraseña");

        jPasswordUsu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblConfClave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblConfClave.setText("Confirmar Contraseña");

        jPasswordConfirUsu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEstado.setText("Estado");

        cmbEstadoUsu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbEstadoUsu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Activo", "Inactivo" }));
        cmbEstadoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoUsuActionPerformed(evt);
            }
        });

        lblIdent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblIdent.setText("Identificación");

        txtIdent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblConfClave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstadoUsu, 0, 323, Short.MAX_VALUE)
                            .addComponent(jPasswordConfirUsu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(jPasswordUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblIdent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdent, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdent, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdent, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClave, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstadoUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPasswordConfirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para verificar si todas las condiciones se cumplen para agegar o modificar un usuario
     * @param nombre un String que representa el nombre del usuario
     * @param ident un String que representa la identificación del usuario
     * @param clave un String que representa la clave de ingreso al sistema
     * @param confirClave un String que representa la clave de ingreso al sistema
     * @param estadoUsu un int representa si el usuario esta activo 1 o 0 inactivo
     * @return un boolean true si cumple las condiciones
     */
    private boolean verificarDatos(String nombre, String ident, String clave, String confirClave, String estadoUsu){
    if(nombre.equalsIgnoreCase("")){
        Ventana.imp("Digite el nombre del Usuario.", "SISTEMA.");
        this.txtNom.grabFocus();
        return false;
    }
    if(ident.equalsIgnoreCase("")){
        Ventana.imp("Digite la identificación del Usuario.", "SISTEMA.");
        this.txtNom.grabFocus();
        return false;
    }
    if(clave.equals("")){
        Ventana.imp("Digite la clave del Usuario.", "SISTEMA.");
        this.jPasswordUsu.grabFocus();
        return false;
    }
    if(confirClave.equals("")){
        Ventana.imp("Confirme la clave del Usuario.", "SISTEMA.");
        this.jPasswordConfirUsu.grabFocus();
        return false;
    }
    if(!clave.equals(confirClave)){
        Ventana.imp("Las claves no coinciden.", "SISTEMA.");
        this.jPasswordConfirUsu.setText("");
        this.jPasswordConfirUsu.grabFocus();
        return false;
    }
    if(estadoUsu.equalsIgnoreCase("Seleccione")){
        Ventana.err("Seleccione el estado del usuario.", "SISTEMA.");
        this.cmbEstadoUsu.grabFocus();
        return false;
    }
    return true;
}

private void iniciar(){
    this.txtNom.grabFocus(); 
    this.cmbEstadoUsu.setSelectedItem("Activo");
    if(this.modificar){   
        this.txtNom.setText(this.myIFormUsuarios.getmyControlador().buscarNombreUsuario(this.idUser));
        this.txtIdent.setText(this.myIFormUsuarios.getmyControlador().buscarIdentUsuario(this.idUser));
        this.jPasswordUsu.setText(this.myIFormUsuarios.getmyControlador().buscarContrasenaUsuario(this.idUser));
        this.jPasswordConfirUsu.setText(this.myIFormUsuarios.getmyControlador().buscarContrasenaUsuario(this.idUser));
        int est = this.myIFormUsuarios.getmyControlador().buscarEstadoUsuario(idUser);
        if(est == 0)
            this.cmbEstadoUsu.setSelectedItem("Inactivo");
        else
            this.cmbEstadoUsu.setSelectedItem("Activo");
    }
}

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:
    String nombre = this.txtNom.getText().trim();
    String usuario = this.txtIdent.getText().trim();
    String clave = this.jPasswordUsu.getText().trim();
    String confirClave = this.jPasswordConfirUsu.getText().trim();
    String estadoUsu = this.cmbEstadoUsu.getSelectedItem().toString();
    String msg;

    if(this.verificarDatos(nombre, usuario, clave, confirClave, estadoUsu)){
        int estUsu = 0;
        if (estadoUsu.equals("Activo"))  
            estUsu = 1; 
        if(this.nuevo){
            if(this.myIFormUsuarios.getmyControlador().
                    registrarUsuarioBD(nombre, usuario, clave, estUsu)){
                msg = "Usuario registrado exitosamente.";
            }
            else {
                msg = "Usuario no se registro."; 
            }
            Ventana.imp(msg, "SISTEMA.");
            this.myIFormUsuarios.cargarTablaUsuarios();
            this.dispose();
        }
        else if(this.modificar){
            if(this.myIFormUsuarios.getmyControlador().
                    editarUsuarioBD(this.idUser, nombre, usuario, clave, estUsu)){
             msg = "Usuario actualizado.";
            }
            else {
                msg = "Usuario no actualizado."; 
            }
            Ventana.imp(msg, "SISTEMA.");
            this.myIFormUsuarios.cargarTablaUsuarios();
            this.dispose();
        }
    }
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarKeyPressed
// TODO add your handling code here:
    int t = (int) evt.getKeyChar();
    if(t == 10){
        this.btnGuardarActionPerformed(null);
    }
}//GEN-LAST:event_btnGuardarKeyPressed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSalirKeyPressed
// TODO add your handling code here:
     int t = (int) evt.getKeyChar();
    if(t == 10){
        this.dispose();
    }
}//GEN-LAST:event_btnSalirKeyPressed

    private void cmbEstadoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoUsuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbEstadoUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordConfirUsu;
    private javax.swing.JPasswordField jPasswordUsu;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblConfClave;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblIdent;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtIdent;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables

}
