/*
 * JDialogFichaProducto.java
 *
 * Created on 3 de marzo de 2014, 01:27 PM
 */

package com.jccr.Vista;

import Complementos.*;

/**
 *
 * @author  JUAN CARLOS
 */
public class JDialogFichaProducto extends javax.swing.JDialog {

    private FormPrincipal myPrincipalForm;
    private IFormProductos myIFormProductos;
    private String nom = "";
    private String terminal;
    private String sesion;
    private int idUser = 0;
    private int id = 0;
    private boolean editar = false; 
    
    /** Creates new form JDialogFichaProducto */
    public JDialogFichaProducto(FormPrincipal myPrincipalForm, boolean modal, IFormProductos myIFormProductos, int id, String nom, 
            boolean editar, String terminal, String sesion, int idUser) {
        super(myPrincipalForm, modal);
        initComponents();
        this.myPrincipalForm = myPrincipalForm;
        this.myIFormProductos = myIFormProductos;
        this.terminal = terminal;
        this.sesion = sesion;
        this.idUser = idUser;
        this.id = id;
        this.editar = editar;
        this.nom = nom;
        this.setLocation();
        this.inicio();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProducto = new javax.swing.JPanel();
        idnun = new javax.swing.JLabel();
        txtNomProducto = new javax.swing.JTextField();
        idnun1 = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox();
        apellido2 = new javax.swing.JLabel();
        idnun2 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        cmdGuardarProducto = new javax.swing.JButton();
        cmdVerificarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Producto");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlProducto.setName("Datos del propietario"); // NOI18N

        idnun.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        idnun.setText("Nombre");

        txtNomProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomProductoKeyPressed(evt);
            }
        });

        idnun1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        idnun1.setText("No");

        txtIdProducto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdProducto.setEnabled(false);

        cmbEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "Activo", "Inactivo" }));

        apellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        apellido2.setText("Estado");

        idnun2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        idnun2.setText("Valor");

        txtPrecioVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPrecioVenta.setEnabled(false);
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });

        cmdGuardarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmdGuardarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Guardar.png"))); // NOI18N
        cmdGuardarProducto.setText("Guardar");
        cmdGuardarProducto.setEnabled(false);
        cmdGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarProductoActionPerformed(evt);
            }
        });

        cmdVerificarProducto.setFont(new java.awt.Font("Tahoma", 1, 14));
        cmdVerificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/15. Buscar.png"))); // NOI18N
        cmdVerificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVerificarProductoActionPerformed(evt);
            }
        });
        cmdVerificarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmdVerificarProductoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdVerificarProductoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idnun, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idnun1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlProductoLayout.createSequentialGroup()
                                        .addComponent(txtNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmdVerificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlProductoLayout.createSequentialGroup()
                                        .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23))
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(idnun2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(cmdGuardarProducto)))
                .addContainerGap())
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idnun1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idnun, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idnun2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(cmdGuardarProducto))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(cmdVerificarProducto)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(11, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public void setLocation(){
    int height = (this.myPrincipalForm.getjdpHeight());
    int width = (this.myPrincipalForm.getjdpWidth());
    this.setLocation ((width - this.getWidth ()) / 2,(height - this.getHeight ()) / 2);
}

public final void inicio(){
    if(this.editar == false){
        this.txtIdProducto.setText(String.valueOf(this.id));
    }
    else{
        this.txtIdProducto.setText(String.valueOf(this.id));
        this.txtNomProducto.setText(this.nom);
        this.consultarProducto();
    }
}
    
public void habilitarCampos(){
    this.txtNomProducto.setEditable(false);
    //this.cmdVerificarProducto.setEnabled(false);
    this.txtPrecioVenta.setEnabled(true);
    this.cmdGuardarProducto.setEnabled(true);
    this.txtPrecioVenta.grabFocus();
}

public void deshabilitarCampos(){
    this.txtNomProducto.setEditable(true);
    //this.cmdVerificarProducto.setEnabled(true);
    this.txtPrecioVenta.setEnabled(false);
    this.cmdGuardarProducto.setEnabled(false);
}

public void limpiarCampos(){
    this.txtNomProducto.setText("");
}

public void consultarProducto(){
    /*int idProd = Integer.parseInt(this.txtIdProducto.getText());
    if(this.myPrincipalForm.getmyEmpresaVentas().verificarProductoId(idProd)){
        this.habilitarCampos();
        this.txtNomProducto.setEditable(true);
        int val = this.myPrincipalForm.getmyEmpresaVentas().buscarPrecioVentaProducto(idProd);
        int estado = this.myPrincipalForm.getmyEmpresaVentas().buscarEstadoProducto(idProd);
        this.txtPrecioVenta.setText(String.valueOf(val));
        if(estado == 1){
            this.cmbEstado.setActionCommand("A");
        }
        else{
            this.cmbEstado.setSelectedItem("I");
        }
    }
    else
        Ventana.imp("El Producto no ha sido registrado.", "SISTEMA");*/
}

private void editarProducto(){
    /*if(this.verificarCampos()){
        int tipo = 1;
        int cantMinima = 0;
        int activo = 1;
        String referencia = "";
        int idProd = Integer.parseInt(this.txtIdProducto.getText());
        String nombreProducto = this.txtNomProducto.getText();
        int precioVenta = Integer.parseInt(this.txtPrecioVenta.getText());
        int precioCompra = 0;
        int cantActual = 0;
        int cantCompra = 0;
        cantActual = cantActual + cantCompra;
        String estado = this.cmbEstado.getSelectedItem().toString();
        if(estado.equalsIgnoreCase("Activo"))
            activo = 1;
        else 
            if(estado.equalsIgnoreCase("Inactivo"))
                activo = 0;
        String msg = this.myPrincipalForm.getmyEmpresaVentas().modProductoBD(idProd, referencia, nombreProducto.toUpperCase(), 
                precioCompra, precioVenta, cantActual, cantMinima, tipo, activo);
        this.myIFormProductos.cargarTablaProductos("where activo = '1' ");
        if(msg.equalsIgnoreCase("La informacion del Producto ha sido modificada exitosamente.")){
            Ventana.imp(msg, "SISTEMA");
            this.dispose();
        }
        else
            Ventana.imp(msg, "SISTEMA");
    }*/
}

private void agregarProducto(){
    /*if(this.verificarCampos()){
        int tipoVenta = 1;
        int cantMinima = 0;
        int activo = 1;
        int idProd = Integer.parseInt(this.txtIdProducto.getText());
        String referencia = "";
        String nombreProducto = this.txtNomProducto.getText();
        int precioCompra = 0;
        int precioVenta = Integer.parseInt(this.txtPrecioVenta.getText());
        int cantActual = 0;
        String estado = this.cmbEstado.getSelectedItem().toString();
        if(estado.equalsIgnoreCase("Activo"))
            activo = 1;
        else 
            if(estado.equalsIgnoreCase("Inactivo"))
                activo = 0;
        String msg = this.myPrincipalForm.getmyEmpresaVentas().registrarProductoBD(idProd, referencia, 
                nombreProducto.toUpperCase(), precioCompra, precioVenta, cantActual, cantMinima, tipoVenta, activo);
        if(msg.equalsIgnoreCase("Producto ingresado exitosamente.")){
            Ventana.imp(msg, "SISTEMA");
            this.limpiarCampos();
            this.deshabilitarCampos();
            this.myIFormProductos.cargarTablaProductos("where activo = '1' ");
            this.dispose();
        }
        else
            Ventana.imp(msg, "SISTEMA");
    }*/
}

private boolean verificarCampos(){
    String estado = this.cmbEstado.getSelectedItem().toString();
    if(estado.equalsIgnoreCase("Seleccione")){
        Ventana.err("Seleccione el estado del producto.", "SISTEMA");
        this.cmbEstado.grabFocus();
        return false;
    }
    return true;
}

private void txtNomProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomProductoKeyPressed
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdVerificarProductoActionPerformed(null);
    }
}//GEN-LAST:event_txtNomProductoKeyPressed

private void txtPrecioVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyPressed
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdGuardarProductoActionPerformed(null);
    }
}//GEN-LAST:event_txtPrecioVentaKeyPressed

private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
// TODO add your handling code here:
    this.txtPrecioVenta.setText(this.txtPrecioVenta.getText().trim());
    if(this.txtPrecioVenta.getText().length() >= 10) {
        evt.consume();
    } 
    else {
        int ascii = evt.getKeyChar();
        if(ascii < 48 || ascii > 57) {
            evt.consume();
        }
    }
}//GEN-LAST:event_txtPrecioVentaKeyTyped

private void cmdGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarProductoActionPerformed
// TODO add your handling code here:
    if(this.editar == false){
        this.agregarProducto();
    }
    else{
        this.editarProducto();
    }
}//GEN-LAST:event_cmdGuardarProductoActionPerformed

private void cmdVerificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVerificarProductoActionPerformed
// TODO add your handling code here:
    /*String nombreProducto = this.txtNomProducto.getText();
    if(nombreProducto.equalsIgnoreCase("")){
            Ventana.imp("Digite el nombre del producto.", "SISTEMA");
            this.txtNomProducto.grabFocus();
            return;
    }
    if(this.myPrincipalForm.getmyEmpresaVentas().verificarProductoNom (nombreProducto.toUpperCase()))
            Ventana.imp("El producto ya ha sido registrado en la base de datos", "SISTEMA");
    else{
        this.habilitarCampos();
    }*/
}//GEN-LAST:event_cmdVerificarProductoActionPerformed

private void cmdVerificarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdVerificarProductoKeyPressed
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdVerificarProductoActionPerformed(null);
    }
}//GEN-LAST:event_cmdVerificarProductoKeyPressed

private void cmdVerificarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdVerificarProductoKeyTyped
// TODO add your handling code here:
    int t=(int) evt.getKeyChar();
    if(t==10){
        this.cmdVerificarProductoActionPerformed(null);
    }
}//GEN-LAST:event_cmdVerificarProductoKeyTyped
   
    /**
    * @param args the command line arguments
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogFichaProducto dialog = new JDialogFichaProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido2;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JButton cmdGuardarProducto;
    private javax.swing.JButton cmdVerificarProducto;
    private javax.swing.JLabel idnun;
    private javax.swing.JLabel idnun1;
    private javax.swing.JLabel idnun2;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtNomProducto;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables

}
